[package]
name = "pixie_wrangler"
version = "0.5.0"
authors = []
edition = "2021"
repository = "https://github.com/rparrett/pixie_wrangler"
license = "MIT OR Apache-2.0"

[features]
debugdump = ["bevy_mod_debugdump"]

[dependencies]

bevy = { version = "0.13", default-features = false, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "multi-threaded",
    "webgl2",
    "x11",
] }

bevy_prototype_lyon = "0.11"
bevy_easings = "0.13"
bevy_common_assets = { version = "0.10", features = ["ron"] }
bevy_mod_debugdump = { version = "0.10", optional = true }

rand = "0.8"
petgraph = "0.6"
itertools = "0.10"
serde = { version = "1", features = ["derive"] }
ron = "*"
rstar = "0.11"

# Dependencies for WASM only.
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["console", "Window", "Storage"] }

[lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"
doc_markdown = "warn"
manual_let_else = "warn"
redundant_else = "warn"
match_same_arms = "warn"
semicolon_if_nothing_returned = "warn"
map_flatten = "warn"

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
