[package]
name = "pixie_wrangler"
version = "0.2.1"
authors = []
edition = "2021"
repository = "https://github.com/rparrett/pixie_wrangler"
license = "MIT OR Apache-2.0"

[dependencies]

bevy = "0.7"

bevy_prototype_lyon = "0.5"
bevy_easings = "0.7"
bevy_asset_ron = "0.4"

rand = "0.8"
petgraph = "0.6"
itertools = "0.10"
serde = {version = "1", features = ["derive"]}
ron = "*"
rstar = "0.9"

# Dependencies for WASM only.
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = {version="0.3", features = ["console", "Window", "Storage"]}

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3