[package]
name = "pixie_wrangler"
version = "0.1.0"
authors = []
edition = "2021"
repository = "https://github.com/rparrett/pixie_wrangler"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bevy = { version = "0.6", default-features=false, features = ["bevy_winit", "render", "png"] }

bevy_prototype_lyon = "0.4"
bevy_easings = "0.5"
bevy_asset_ron = "0.3"

rand = "0.8"
petgraph = "0.6"
itertools = "0.10"
serde = {version = "1", features = ["derive"]}
ron = "*"

# Dependencies for native only.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = { version = "0.1" }

# Dependencies for WASM only.
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.1", features = ["wasm-bindgen"] }
web-sys = {version="0.3", features = ["console", "Window", "Storage"]}

[profile.dev]
opt-level = 1

[profile.release]
# lto = true
# opt-level = 's'

[patch.crates-io]
wgpu = { git = "https://github.com/rparrett/wgpu.git", branch="fix-taipo" }